author: WZP
favorite:
  luckynumber: 999
  music:
  - zui xuan min zu feng
  sport:
  - swimming
  - football
information:
  age: "37"
  alise:
  - Lion
  - NK
  - KaQS
  image: /path/header.rpg
  name: Harry
  public: false
passwd: Hello
timestamp: "2018-07-16 10:23:19"
version: 1.1.1
